### ISSUE TITLE
Credential Provider is null

### ISSUE THREAD

**Issue by bdcheung** [SwipeX/PokeMate#102]
`java -jar Pokemate.jar` with build 0.1.9 produces the following error:

```
java.util.NoSuchElementException: No line found
    at java.util.Scanner.nextLine(Scanner.java:1540)
    at dekk.pw.pokemate.Context.Login(Context.java:47)
    at dekk.pw.pokemate.Context.Login(Context.java:37)
    at dekk.pw.pokemate.PokeMate.<init>(PokeMate.java:39)
    at dekk.pw.pokemate.PokeMate.main(PokeMate.java:55)
Logged in as $USERNAME@gmail.com
Exception in thread "main" com.pokegoapi.exceptions.LoginFailedException: Credential Provider is null
    at com.pokegoapi.api.PokemonGo.<init>(PokemonGo.java:66)
    at dekk.pw.pokemate.PokeMate.<init>(PokeMate.java:41)
    at dekk.pw.pokemate.PokeMate.main(PokeMate.java:55)
```

**Comment by bdcheung** [comment]
Here is the `config.properties`:

```
# PTC/Google login credentials
username=$USERNAME@gmail.com
password=$PASSWORD
#Lat/Long
latitude=XX.XXXXXX
longitude=-XX.XXXXXX
#Preferred throw item
preferred_ball=ITEM_POKE_BALL
#Google maps API key for walking
api-key=$GOOGLE_API_KEY
#What IV% to keep pokemon at
iv-ratio=90
#What CP to keep pokemon above
min-cp=1000
#show user interface
show=true
# should the bot EVER drop items (true/false)
drop_items=false
# Meters per second
speed=2.00
# Automatic evolving
automatic-evolving=true
#Range to walk in, VERY sensitive
range=.005
#points in the map path
map-points=35
# Only whitelist certain pokemons
whitelisted_pokemon=
# List of Pokémons ids to NEVER transfer, separated by commas.
never-transfer=
```

**Comment by bdcheung** [comment]
Compiling from source removes the error

**Comment by SonnyX** [comment]
Try removing token.txt

**Comment by bdcheung** [comment]
Yep, cleaning out the token cache fixed it.  That makes sense as the token-based auth was added in e99f7b3

**Comment by arkdelkaos** [comment]
Where is the `token.txt` file?

**Comment by GerardSmit** [comment]
@arkdelkaos Since the new version; tokens can be found under the folder `tokens`. Every account has his own file. (If you used only one account, there is probably one file).
