### ISSUE TITLE
[BUG] Only receive error if interface is set to false 

### ISSUE THREAD

**Issue by Sorries** [SwipeX/PokeMate#103]
If I set the show user interface to false,

I get this error 

`Exception in thread "Thread-1" java.lang.IllegalStateException: Toolkit not initialized
    at com.sun.javafx.application.PlatformImpl.runLater(PlatformImpl.java:273)
    at com.sun.javafx.application.PlatformImpl.runLater(PlatformImpl.java:268)
    at javafx.application.Platform.runLater(Platform.java:83)
    at dekk.pw.pokemate.PokeMateUI.toast(PokeMateUI.java:244)
    at dekk.pw.pokemate.tasks.TagPokestop.lambda$run$0(TagPokestop.java:35)
    at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
    at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
    at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
    at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
    at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
    at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
    at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
    at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
    at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
    at dekk.pw.pokemate.tasks.TagPokestop.run(TagPokestop.java:31)
    at dekk.pw.pokemate.tasks.TaskController.lambda$run$0(TaskController.java:41)
    at java.util.ArrayList.forEach(ArrayList.java:1249)
    at dekk.pw.pokemate.tasks.TaskController.run(TaskController.java:41)`

**Comment by oplosthee** [comment]
This is a duplicate issue of https://github.com/SwipeX/PokeMate/issues/99
