### ISSUE TITLE
bug?

### ISSUE THREAD

**Issue by pikachukaki** [SwipeX/PokeMate#140]
Im not sure what is this but after some time it spam the cmd and nothing happent in the app...need to restart the app to continue working!

com.pokegoapi.exceptions.RemoteServerException: Got a unexpected http code : 502
        at com.pokegoapi.main.RequestHandler.sendServerRequests(RequestHandler.java:109)
        at com.pokegoapi.api.inventory.ItemBag.removeItem(ItemBag.java:76)
        at dekk.pw.pokemate.tasks.DropItems.run(DropItems.java:28)
        at java.util.ArrayList.forEach(Unknown Source)
        at dekk.pw.pokemate.tasks.TaskController.run(TaskController.java:52)

**Comment by RobertMcCoy** [comment]
Delete your Token's folder and re-run the program.

**Comment by SwipeX** [comment]
502 error means no response from the PGO servers

**Comment by pikachukaki** [comment]
now stays here 
D/RequestHandler: Authenticated with static token
and nothing happens

**Comment by BurakDev** [comment]
@pikachukaki This is a PGO servers issue. Check http://ispokemongodownornot.com/

**Comment by pikachukaki** [comment]
yeah its working thanks!!!
