### ISSUE TITLE
Raspberry

### ISSUE THREAD

**Issue by veskoz** [SwipeX/PokeMate#166]
Hey, first of all thank you.
I'm trying to use your bot in my Raspberry Pi2 with Raspbian.
I've installed java, then when i do sudo java -jar Pokemate.jar i get this error:

```
Exception in thread "main" java.lang.NoClassDefFoundError: javafx/application/Ap                             plication
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:14                             2)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at dekk.pw.pokemate.PokeMate.<init>(PokeMate.java:35)
        at dekk.pw.pokemate.PokeMate.main(PokeMate.java:83)
Caused by: java.lang.ClassNotFoundException: javafx.application.Application
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 14 more
```

Looks like JavaFX is not installed but i'm kinda sure it is.
Does someone have any idea?

**Comment by mark3717** [comment]
Did you rename config.properties.template to config.properties?
I did it on osx in the finder, but it didn't work properly. After renaming it through the terminal it worked...

**Comment by SippieCup** [comment]
Update Java. Raspbian comes with Java SE7 installed, which does not include JavaFX. 

You need to install Java SE 8u102 to run the bot.

https://wiki.openjdk.java.net/display/OpenJFX/OpenJFX+on+the+Raspberry+Pi

**Comment by veskoz** [comment]
This is what i have installed:
pi@raspberrypi:~ $ java -version
java version "1.8.0_101"
Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
Java HotSpot(TM) Client VM (build 25.101-b13, mixed mode)

P.S. i don not ha a monitor plugged, i'm using the pi as headless

**Comment by SippieCup** [comment]
> java version "1.8.0_101"

Use 1.8.0_102.

**Comment by BurakDev** [comment]
Set show=false on your configuration file if you don't have monitor plugged

**Comment by veskoz** [comment]
all right, i'll try this afternoon, thank you all

**Comment by kylestev** [comment]
Make sure you have the non-headless version of Java installed. The headless version will not have JavaFX.

**Comment by veskoz** [comment]
Ok, now it's working.
I was messing up with sudo and not sudo.
Thank you.
