### ISSUE TITLE
Bot was running - stopped catching/hitting stops, on kill/reload getting an error.

### ISSUE THREAD

**Issue by sahaq** [SwipeX/PokeMate#167]
Windows 10 host, java/etc up to date.

Exception in thread "main" com.pokegoapi.exceptions.RemoteServerException: com.google.protobuf.InvalidProtocolBufferException: Contents of buffer are null
        at com.pokegoapi.api.player.PlayerProfile.updateProfile(PlayerProfile.java:85)
        at com.pokegoapi.api.player.PlayerProfile.<init>(PlayerProfile.java:67)
        at com.pokegoapi.api.PokemonGo.<init>(PokemonGo.java:75)
        at dekk.pw.pokemate.PokeMate.<init>(PokeMate.java:66)
        at dekk.pw.pokemate.PokeMate.main(PokeMate.java:83)
Caused by: com.google.protobuf.InvalidProtocolBufferException: Contents of buffer are null
        at com.pokegoapi.main.ServerRequest.getData(ServerRequest.java:66)
        at com.pokegoapi.api.player.PlayerProfile.updateProfile(PlayerProfile.java:83)
        ... 4 more

**Comment by EiTeR94** [comment]
Servers are actually overload/down
http://ispokemongodownornot.com/

That may be the cause

**Comment by SippieCup** [comment]
This is now Handled Gracefully and won't effect the bot.
