### ISSUE TITLE
ProtoBuf: "Contents of buffer are null"

### ISSUE THREAD

**Issue by nastye** [SwipeX/PokeMate#168]
I just upgraded to 0.2.1, got past the changed login, but it seems the bot doesn't get the responses it's looking for. Happens every time after logging in, with/without sudo, Java 1.8.0_92. I checked on a phone, and I can still log in at least. From the looks of it, my token isn't okay?

`D/GoogleCredentialProvider: 3600
D/GoogleCredentialProvider: Refreshed Token ---
Logged in as ---
D/RequestHandler: Authenticated with static token
D/RequestHandler: Authenticated with static token
Exception in thread "main" com.pokegoapi.exceptions.RemoteServerException: com.google.protobuf.InvalidProtocolBufferException: Contents of buffer are null
    at com.pokegoapi.api.player.PlayerProfile.updateProfile(PlayerProfile.java:85)
    at com.pokegoapi.api.player.PlayerProfile.<init>(PlayerProfile.java:67)
    at com.pokegoapi.api.PokemonGo.<init>(PokemonGo.java:75)
    at dekk.pw.pokemate.PokeMate.<init>(PokeMate.java:66)
    at dekk.pw.pokemate.PokeMate.main(PokeMate.java:83)
Caused by: com.google.protobuf.InvalidProtocolBufferException: Contents of buffer are null
    at com.pokegoapi.main.ServerRequest.getData(ServerRequest.java:66)
    at com.pokegoapi.api.player.PlayerProfile.updateProfile(PlayerProfile.java:83)
    ... 4 more`

**Comment by SippieCup** [comment]
Logins are currently down.

**Comment by EiTeR94** [comment]
http://ispokemongodownornot.com/

**Comment by nastye** [comment]
Funny, because I can log in on the phone

**Comment by SippieCup** [comment]
@nastye: Thats because you have a valid login token already.

If you trying to login wiht the bot for the first time, you have to wait for SwipeX to merge the new login code or use the release I posted [here](https://github.com/SippieCup/PokeMate/releases/tag/2.1.1)

**Comment by nastye** [comment]
@SippieCup I've been logged in before too, so I had the token, generated md5 for my login and moved the token.txt accordingly. It's not been the usual issue with "go to null and enter null". It worked now without changing anything, so it really has been an issue with the gameservers responses.
