### ISSUE TITLE
Exception in thread ERROR

### ISSUE THREAD

**Issue by Jarkheld** [SwipeX/PokeMate#183]
Hi, i keep getting this error when i try to connect via: java -jar Pokemate.jar.
I'm using Pokemate version 0.2.0, everything worked as intended during the past days, this is the first time that i see this type of error, is there any way to fix it?

Exception in thread "main" com.pokegoapi.exceptions.RemoteServerException: Got a
 unexpected http code : 502
        at com.pokegoapi.main.RequestHandler.sendServerRequests(RequestHandler.j
ava:109)
        at com.pokegoapi.main.RequestHandler.sendServerRequests(RequestHandler.j
ava:133)
        at com.pokegoapi.api.player.PlayerProfile.updateProfile(PlayerProfile.ja
va:79)
        at com.pokegoapi.api.player.PlayerProfile.<init>(PlayerProfile.java:67)
        at com.pokegoapi.api.PokemonGo.<init>(PokemonGo.java:75)
        at dekk.pw.pokemate.PokeMate.<init>(PokeMate.java:67)
        at dekk.pw.pokemate.PokeMate.main(PokeMate.java:83)

Thank you so much,
Jarkheld

**Comment by lok0919** [comment]
According to https://github.com/SwipeX/PokeMate/wiki
502 should be login server problem

**Comment by kylestev** [comment]
http://www.mmoserverstatus.com/pokemon_go
