### ISSUE TITLE
Various errors

### ISSUE THREAD

**Issue by Jarkheld** [SwipeX/PokeMate#191]
Hi! When i try to lounch the new 0.2.5 version, using java -jar Pokemate.jar, I get a lot of errors like the following ones:
 at java.util.regex.Pattern$Branch.match(Unknown Source)
 at java.util.regex.Pattern$GroupHead.match(Unknown Source)
whose cause the exectution to stop. Is there any way to fix them?

0.2.0 version seems to work as intened (i had to assing the "false" attribute to drop_items for it to work) but i get a lot of errors like those ones:
com.pokegoapi.exceptions.RemoteServerException: com.google.protobuf.InvalidProto
colBufferException: Contents of buffer are null
        at com.pokegoapi.api.inventory.Inventories.updateInventories(Inventories
.java:114)
        at com.pokegoapi.api.inventory.Inventories.updateInventories(Inventories
.java:84)
        at com.pokegoapi.api.inventory.Hatchery.queryHatchedEggs(Hatchery.java:7
5)
        at dekk.pw.pokemate.tasks.HatchEgg.run(HatchEgg.java:21)
        at java.util.ArrayList.forEach(Unknown Source)
        at dekk.pw.pokemate.tasks.TaskController.run(TaskController.java:52)
Caused by: com.google.protobuf.InvalidProtocolBufferException: Contents of buffe
r are null
        at com.pokegoapi.main.ServerRequest.getData(ServerRequest.java:66)
        at com.pokegoapi.api.inventory.Inventories.updateInventories(Inventories
.java:112)
        ... 5 more

Everything worked fin untill late evening, how do i fix them?

Thank you very much :D

**Comment by iDreamInBinary** [comment]
#185 #190 

Stop creating new issues if your errors are already discussed in existing issues...

**Comment by Jarkheld** [comment]
thank you so much!

**Comment by SippieCup** [comment]
Fixed in my new release, Compiling from source might be a problem until jitpack resolves its issues.

https://github.com/SippieCup/PokeMate/releases/tag/2.3.5

**Comment by SippieCup** [comment]
Duplicate Issue, Closing thread.
