### ISSUE TITLE
Still getting same error in 0.2.6

### ISSUE THREAD

**Issue by thatsmyface** [SwipeX/PokeMate#202]
Exception in thread "main" com.pokegoapi.exceptions.RemoteServerException: com.google.protobuf.InvalidProtocolBufferException: Contents of buffer are null
    at com.pokegoapi.api.inventory.Inventories.updateInventories(Inventories.java:114)
    at com.pokegoapi.api.inventory.Inventories.updateInventories(Inventories.java:84)
    at com.pokegoapi.api.PokemonGo.<init>(PokemonGo.java:90)
    at dekk.pw.pokemate.PokeMate.<init>(PokeMate.java:62)
    at dekk.pw.pokemate.PokeMate.main(PokeMate.java:93)
Caused by: com.google.protobuf.InvalidProtocolBufferException: Contents of buffer are null
    at com.pokegoapi.main.ServerRequest.getData(ServerRequest.java:66)
    at com.pokegoapi.api.inventory.Inventories.updateInventories(Inventories.java:112)
    ... 4 more

Is there any fix for this? (Sorry if this is a repeat issue)

**Comment by SwipeX** [comment]
There has been alot of server changes from niantic, and this means they sent back blank data.

**Comment by thatsmyface** [comment]
So what I'm hearing is there's no fix for this?

**Comment by veskoz** [comment]
I think there's no fix YET.
Let @SwipeX some time to release a new one.

**Comment by thatsmyface** [comment]
Okay, I'm just saying if it's coming from Niantic's side there isn't much we can do except not log the error.

**Comment by thatsmyface** [comment]
But I'm willing to see what SwipeX comes up with

**Comment by SwipeX** [comment]
They aren't going to be able to change an API infrastructure overnight, so it's not over yet. They are rate limiting now (Which is not fixed yet), and they changed to OAuth2 authentications (which I pushed a solution for)
