### ISSUE TITLE
NullPointerException at dekk.pw.pokemate.tasks.EvolvePokemon.run(EvolvePokemon.java:55)

### ISSUE THREAD

**Issue by SSinischo** [SwipeX/PokeMate#204]
Shortly after running the script.  Stops after this.

[10:01:31] - Goldeen has evolved into Seaking costing 50 candies
Exception in thread "Thread-2" java.lang.NullPointerException
        at dekk.pw.pokemate.tasks.EvolvePokemon.run(EvolvePokemon.java:55)
        at java.util.ArrayList.forEach(Unknown Source)
        at dekk.pw.pokemate.tasks.TaskController.run(TaskController.java:52)

**Comment by gsisso** [comment]
thats because of the issue of buffer being null,what I did for now to resolve it is checking that "result" isnt null

**Comment by SippieCup** [comment]
This error is now handled gracefully and will hang the bot.
