### ISSUE TITLE
Requires X11, even when show=false

### ISSUE THREAD

**Issue by Gillingham** [SwipeX/PokeMate#207]
```
$ grep show config.properties
#show user interface
show=false
```

```
$ java -jar Pokemate.jar
Using default config.properties location
-----------------------------------------
  Please go to the following URL
https://accounts.google.com/o/oauth2/auth*hidden*
Exception in thread "main" java.awt.AWTError: Can't connect to X11 window server using 'localhost:10.0' as the value of the DISPLAY variable.
        at sun.awt.X11GraphicsEnvironment.initDisplay(Native Method)
        at sun.awt.X11GraphicsEnvironment.access$200(X11GraphicsEnvironment.java:65)
        at sun.awt.X11GraphicsEnvironment$1.run(X11GraphicsEnvironment.java:115)
        at java.security.AccessController.doPrivileged(Native Method)
        at sun.awt.X11GraphicsEnvironment.<clinit>(X11GraphicsEnvironment.java:74)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:264)
        at java.awt.GraphicsEnvironment.createGE(GraphicsEnvironment.java:103)
        at java.awt.GraphicsEnvironment.getLocalGraphicsEnvironment(GraphicsEnvironment.java:82)
        at sun.awt.X11.XToolkit.<clinit>(XToolkit.java:126)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:264)
        at java.awt.Toolkit$2.run(Toolkit.java:860)
        at java.awt.Toolkit$2.run(Toolkit.java:855)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.awt.Toolkit.getDefaultToolkit(Toolkit.java:854)
        at java.awt.Desktop.isDesktopSupported(Desktop.java:169)
        at java.awt.Desktop.getDesktop(Desktop.java:143)
        at dekk.pw.pokemate.Context.Login(Context.java:88)
        at dekk.pw.pokemate.Context.Login(Context.java:49)
        at dekk.pw.pokemate.PokeMate.<init>(PokeMate.java:59)
        at dekk.pw.pokemate.PokeMate.main(PokeMate.java:93)
```

**Comment by SwipeX** [comment]
I see this stems from the ability to launch the javafx in `Application.launch`. Not sure what can be done on this, but ill label it as a bug for now.

**Comment by SonnyX** [comment]
@SwipeX It's actually probably the following line causing the problem in PokeMate.java

```
String access = JOptionPane.showInputDialog("Enter authorization code: ");
```

**Comment by Gillingham** [comment]
Just doing more testing, in a tmux session without X11 forwarding setup I get the first stack trace, if I open a new ssh session with X11 forwarding enabled, and then try I get a different stack trace:

```
java.lang.UnsupportedOperationException: The BROWSE action is not supported on the current platform!
    at java.awt.Desktop.checkActionSupport(Desktop.java:225)
    at java.awt.Desktop.browse(Desktop.java:381)
    at dekk.pw.pokemate.Context.Login(Context.java:88)
    at dekk.pw.pokemate.Context.Login(Context.java:49)
    at dekk.pw.pokemate.PokeMate.<init>(PokeMate.java:59)
    at dekk.pw.pokemate.PokeMate.main(PokeMate.java:93)
Logged in as *user*
Exception in thread "main" com.pokegoapi.exceptions.LoginFailedException: Credential Provider is null
    at com.pokegoapi.api.PokemonGo.<init>(PokemonGo.java:72)
    at dekk.pw.pokemate.PokeMate.<init>(PokeMate.java:62)
    at dekk.pw.pokemate.PokeMate.main(PokeMate.java:93)
```

I assume both are related to this being a headless server, and not a desktop as this project may assume. Not sure if this is intentional or not, so reporting it.

Would be great if this app simply embed a simple web server and let the user use a browser or proxy to it instead of embedding the app inside a web browser toolkit forcing the requirement of a GUI.

**Comment by SwipeX** [comment]
@Gillingham we have plans for pure javascript front end, likely encapsulated by electron. Assuming that niantic isnt running around with lawsuits.

**Comment by SwipeX** [comment]
We could easily surround these gui calls to stop this.

**Comment by SippieCup** [comment]
working on this now. If `show=false`, i'll have the login go through console input.

**Comment by SippieCup** [comment]
Fixed in https://github.com/SwipeX/PokeMate/commit/1f673df13b51bb0be92e2783283235d218b847b5
