### ISSUE TITLE
Is this a known issue? Must provide either API key or Maps for Work credentials.

### ISSUE THREAD

**Issue by pisuth** [SwipeX/PokeMate#209]
java.lang.IllegalStateException: Must provide either API key or Maps for Work credentials.
    at com.google.maps.GeoApiContext.checkContext(GeoApiContext.java:175)
    at com.google.maps.GeoApiContext.getWithPath(GeoApiContext.java:144)
    at com.google.maps.GeoApiContext.get(GeoApiContext.java:104)
    at com.google.maps.PendingResultBase.makeRequest(PendingResultBase.java:78)
    at com.google.maps.PendingResultBase.await(PendingResultBase.java:55)
    at dekk.pw.pokemate.tasks.Navigate.queryDirections(Navigate.java:135)
    at dekk.pw.pokemate.tasks.Navigate.populateDirections(Navigate.java:157)
    at dekk.pw.pokemate.tasks.Navigate.<init>(Navigate.java:42)
    at dekk.pw.pokemate.tasks.TaskController.<init>(TaskController.java:21)
    at dekk.pw.pokemate.PokeMate.<init>(PokeMate.java:73)

**Comment by SwipeX** [comment]
you need an api_key

**Comment by pisuth** [comment]
It is there... I guess it's just on my end then. Let me check it myself. Thanks

**Comment by pisuth** [comment]
So the problem was api-key changed to api_key... jesus

**Comment by SippieCup** [comment]
Please note that all config options are now using an underscore ("_")
