### ISSUE TITLE
How do I even start the bot with this error?

### ISSUE THREAD

**Issue by creliuz** [SwipeX/PokeMate#210]
I've read in both wiki and "readme" and i've put my gmail and password inside config.properties. When I try to run (with cmd) the Pokemate.jar using this code "java -jar Pokemate.jar" I get this error: 

"D:\Program Files\GitHub\PokeMate>java -jar Pokemate.jar
Using default config.properties location
Exception in thread "main" java.lang.NumberFormatException: For input string: "35,688271"
        at sun.misc.FloatingDecimal.readJavaFormatString(Unknown Source)
        at sun.misc.FloatingDecimal.parseDouble(Unknown Source)
        at java.lang.Double.parseDouble(Unknown Source)
        at dekk.pw.pokemate.PokeMate.<init>(PokeMate.java:51)
        at dekk.pw.pokemate.PokeMate.main(PokeMate.java:93)"

What to do? In what foulder should Pokemate.jar be and how do I even compile and run Pokemate.java?
I'm lost. .___.

**Comment by SippieCup** [comment]
Your (likely latitude) number has a comma rather than a period for the decimal point. Just change that and it'll work :)

**Comment by creliuz** [comment]
@SippieCup  woow thx! well I got it started but now it shows another error :(

D/RequestHandler: Authenticated with static token
D/RequestHandler: Authenticated with static token
Exception in thread "main" com.pokegoapi.exceptions.RemoteServerException: com.google.protobuf.InvalidProtocolBufferException: Contents of buffer are null
        at com.pokegoapi.api.settings.Settings.updateSettings(Settings.java:88)
        at com.pokegoapi.api.settings.Settings.<init>(Settings.java:70)
        at com.pokegoapi.api.PokemonGo.<init>(PokemonGo.java:86)
        at dekk.pw.pokemate.PokeMate.<init>(PokeMate.java:62)
        at dekk.pw.pokemate.PokeMate.main(PokeMate.java:93)
Caused by: com.google.protobuf.InvalidProtocolBufferException: Contents of buffer are null
        at com.pokegoapi.main.ServerRequest.getData(ServerRequest.java:66)
        at com.pokegoapi.api.settings.Settings.updateSettings(Settings.java:86)
        ... 4 more

Any ideas?

**Comment by creliuz** [comment]
A second try, another error: 

Exception in thread "main" com.pokegoapi.exceptions.RemoteServerException: Got a unexpected http code : 502
        at com.pokegoapi.main.RequestHandler.sendServerRequests(RequestHandler.java:111)
        at com.pokegoapi.api.player.PlayerProfile.updateProfile(PlayerProfile.java:90)
        at com.pokegoapi.api.player.PlayerProfile.<init>(PlayerProfile.java:78)
        at com.pokegoapi.api.PokemonGo.<init>(PokemonGo.java:82)
        at dekk.pw.pokemate.PokeMate.<init>(PokeMate.java:62)
        at dekk.pw.pokemate.PokeMate.main(PokeMate.java:93)

**Comment by BurakDev** [comment]
Those errors mean PokemonGo servers are down. Retry later ! Check status here http://ispokemongodownornot.com/

**Comment by creliuz** [comment]
Alright, thanks! @BurakDev
