### ISSUE TITLE
Egg hatching not working

### ISSUE THREAD

**Issue by ickis098** [SwipeX/PokeMate#222]
I have 7,7 out of 5km egg (e.g. 154%) and still not hatched.
The console showing: 
`com.pokegoapi.exceptions.RemoteServerException: com.google.protobuf.InvalidProto
colBufferException: Contents of buffer are null
        at com.pokegoapi.api.inventory.Inventories.updateInventories(Inventories.java:114)
        at com.pokegoapi.api.inventory.EggIncubator.hatchEgg(EggIncubator.java:81)
        at dekk.pw.pokemate.tasks.IncubateEgg.run(IncubateEgg.java:41)
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Caused by: com.google.protobuf.InvalidProtocolBufferException: Contents of buffer are null
        at com.pokegoapi.main.ServerRequest.getData(ServerRequest.java:66)
        at com.pokegoapi.api.inventory.Inventories.updateInventories(Inventories
.java:112)
        ... 7 more`

**Comment by kylestev** [comment]
this means you are rate limited by Niantics servers

**Comment by SippieCup** [comment]
Going one step further I tried to solve this (which led to the locking I implemented) and the issue comes from the API, I don't know what can be done about hatching eggs until the API is updated.

**Comment by ickis098** [comment]
" this means you are rate limited by Niantics servers"
What does this mean? Have I done (or set-up) something wrong? Or is it just the way how Niantic devs are protecting against bots?

**Comment by kylestev** [comment]
the latter. they're starting to fight back and detect boys using their API faster than humans could.

**Comment by SippieCup** [comment]
Its just the way niantic are dealing with clients running faster than they should. You can only make ~3 requests to the server every second, otherwise it just sends you nothing (that error). The hatching function in the API does ~4 or 5 in 1 second and causes this issue.

**Comment by ickis098** [comment]
By the API you mean Niantic's API? Or is it how the bot is using it? I suppose it can't be Niantics, as then the egg hatching would not work also in their own app, right?

**Comment by SippieCup** [comment]
The API is the platform we use to commuicate with Niantic, it can be found [here](https://github.com/Grover-c13/PokeGOAPI-Java). It takes care of the work of formatting the requests and parsing the response so we can focus on the bot development.

**Comment by ickis098** [comment]
Oh, right, i see. Thanks for explanation..

**Comment by SippieCup** [comment]
fixed in newest release. closing thread.
