### ISSUE TITLE
New Version fail start

### ISSUE THREAD

**Issue by Zaius393** [SwipeX/PokeMate#226]
Probably is my fault about put the correct string:
C:\Users\giuli\Desktop\Pkemon bot>java -jar pokemate-0.3.0.jar
Using default config.properties location
Exception in thread "main" java.lang.NumberFormatException: For input string: "false"
        at java.lang.NumberFormatException.forInputString(Unknown Source)
        at java.lang.Integer.parseInt(Unknown Source)
        at java.lang.Integer.parseInt(Unknown Source)
        at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
        at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
        at java.util.Spliterators$ArraySpliterator.forEachRemaining(Unknown Source)
        at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source)
        at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
        at java.util.stream.ReferencePipeline.forEach(Unknown Source)
        at dekk.pw.pokemate.Config.fillList(Config.java:123)
        at dekk.pw.pokemate.Config.load(Config.java:76)
        at dekk.pw.pokemate.PokeMate.main(PokeMate.java:96)
I don't know why is not start

**Comment by SippieCup** [comment]
Your configuration file is misconfigured.

Please remove any personal/private details from the config file such as username, password, GApps API Key, and your location (if it is custom) and post it here and I can double check for you.

**Comment by Zaius393** [comment]
# PTC/Google login credentials

username=
password=

# Location by name: e.g. "Sydney" or "W12 8LP" or "Trafalgar Square, London" - set to true to use

use_location_name=falselocation_by_name="Trafalgar Square, London"

#Lat/Long

latitude=
longitude=

#Preferred throw item
preferred_ball=ITEM_POKE_BALL

#Google maps API key for walking
api_key=

# What IV% to keep pokemon at

iv_ratio=90

# What CP to keep pokemon above

min_cp=1200

# show user interface

show=true

# should the bot EVER drop items (true/false)

drop_items=true

# Meters per second

speed=2.00

# Automatic evolving

automatic_evolving=true

# Range to walk in, VERY sensitive

range=.006

# points in the map path

map_points=30

# Only whitelist certain pokemons

whitelisted_pokemon=10,13,16
,

# List of Pokémons ids to NEVER transfer, separated by commas.

never_transfer=

DRATINI, LAPRAS, EEVEE, SLOWBRO, GAYARDOS, 

# Enable events notifications on console output

console_notification=true

# Enable toast notifications on UI (only if UI is enabled)

ui_notification=true

# Enable popup notifications

sys_notification=false

# Enable auto eggs incubating

eggs_incubating=true

# Enable auto eggs hatching

eggs_hatching=true

# Items to drop (remove from this list if you want to keep it, note that inventory management will now be left up to you, as it could be possible to run out of pokeballs)

drop_item_list=ITEM_POTION,ITEM_RAZZ_BERRY,ITEM_REVIVE,ITEM_MAX_REVIVE

# Minimum amount of each item to save

minimum_item_amount=10

# Minimum CP for a pokemon to have a pop-up message (All pokemon that are caught will still be logged)

minimum_cp_for_ui_message=0

# Prefer IV over CP when transfering? true keeps highest IV, false keeps highest CP

transfer_prefers_iv=true
#navigation type can be either STREETS or POKESTOPS
navigation_type = STREETS

# Ignore catching certain pokemons

ignore_catching_pokemon=false

# should the bot bypass softbans

softban_bypass=

**Comment by Zaius393** [comment]
Sorry for the format it was unwanted

**Comment by ghost** [comment]
Change
`use_location_name=falselocation_by_name="Trafalgar Square, London"`
to
`use_location_name=false`
`location_by_name="Trafalgar Square, London"`

**Comment by xooromat** [comment]
i had a similar problem... try to change the navigation_type.

change
`navigation_type = STREETS`
to
`navigation_type=POKESTOPS`

**Comment by Zaius393** [comment]
PTC/Google login credentials
username=
password=
Location by name: e.g. "Sydney" or "W12 8LP" or "Trafalgar Square, London" - set to true to use
use_location_name=false
location_by_name="Trafalgar Square, London"
Lat/Long
latitude=
longitude=
Preferred throw item
preferred_ball=ITEM_POKE_BALL
Google maps API key for walking
api_key=
What IV% to keep pokemon at
iv_ratio=90
What CP to keep pokemon above
min_cp=1200
show user interface
show=true
should the bot EVER drop items (true/false)
drop_items=true
 Meters per second
speed=2.00
Automatic evolving
automatic_evolving=true
 Range to walk in, VERY sensitive
range=.006

points in the map path
map_points=30
 Only whitelist certain pokemons
whitelisted_pokemon=10,13,16
, List of Pokémons ids to NEVER transfer, separated by commas.
never_transfer=  
 Enable events notifications on console output
console_notification=true

 Enable toast notifications on UI (only if UI is enabled)
ui_notification=true
 Enable popup notifications
sys_notification=true
 Enable auto eggs incubating
eggs_incubating=true
Enable auto eggs hatching
eggs_hatching=true
Items to drop (remove from this list if you want to keep it, note that inventory management will now be left up to you, as it could be possible to run out of pokeballs)
drop_item_list=ITEM_POTION,ITEM_RAZZ_BERRY,ITEM_REVIVE,ITEM_MAX_REVIVE
Minimum amount of each item to save
minimum_item_amount=10
Minimum CP for a pokemon to have a pop-up message (All pokemon that are caught will still be logged)
minimum_cp_for_ui_message=0
Prefer IV over CP when transfering? true keeps highest IV, false keeps highest CP
transfer_prefers_iv=true
navigation type can be either STREETS or POKESTOPS
navigation_type = POKESTOPS

# Ignore catching certain pokemons

ignore_catching_pokemon=false
should the bot bypass softbans
softban_bypass=false

i have tried but it continue like that : 
C:\Users\giuli\Desktop\Pkemon bot>java -jar pokemate-0.3.0.jar
Using default config.properties location
Exception in thread "main" java.lang.NumberFormatException: For input string: "false"
        at java.lang.NumberFormatException.forInputString(Unknown Source)
        at java.lang.Integer.parseInt(Unknown Source)
        at java.lang.Integer.parseInt(Unknown Source)
        at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
        at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
        at java.util.Spliterators$ArraySpliterator.forEachRemaining(Unknown Source)
        at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source)
        at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
        at java.util.stream.ReferencePipeline.forEach(Unknown Source)
        at dekk.pw.pokemate.Config.fillList(Config.java:123)
        at dekk.pw.pokemate.Config.load(Config.java:76)
        at dekk.pw.pokemate.PokeMate.main(PokeMate.java:96)

**Comment by gsisso** [comment]
the ignore catching pokemon isnt a true/false config,its an a list of numbers this is why you get this error.

if you dont want it to ignore pokemons just leave it blank,if you want it to ignore pidgey and rattata use
`ignore_catching_pokemon=16,19`

**Comment by Zaius393** [comment]
@gsplash it was that , thank you and thank you all for the support
