### ISSUE TITLE
Failed to Start on Ubuntu 16.04

### ISSUE THREAD

**Issue by Shazgul** [SwipeX/PokeMate#229]
xxx@xxx-xxx:~/PokemonGoBot/SwipeX$ java -jar pokemate-0.3.0.jar
Using default config.properties location
Logged in as xxx
D/RequestHandler: Authenticated with static token
D/RequestHandler: Authenticated with static token
Exception in thread "main" java.lang.IllegalAccessError: class dekk.pw.pokemate.Context (in unnamed module @0xe356f0) cannot access class com.sun.corba.se.impl.orbutil.concurrent.Mutex (in module java.corba) because module java.corba does not export com.sun.corba.se.impl.orbutil.concurrent to unnamed module @0xe356f0
    at dekk.pw.pokemate.Context.<init>(Context.java:40)
    at dekk.pw.pokemate.PokeMate.<init>(PokeMate.java:68)
    at dekk.pw.pokemate.PokeMate.main(PokeMate.java:97)

Using Ubuntu 16.04 & OpenJDK 9

**Comment by SippieCup** [comment]
I don't know how well pokemate runs on JDK9. I would suggest using 8.102 if possible

**Comment by Shazgul** [comment]
Okay using OpenJDK 8 now, it's running but the Bot just puts these messages out:

D/RequestHandler: Authenticated with static token
D/RequestHandler: Authenticated with static token
Jul 31, 2016 4:11:09 PM com.google.maps.OkHttpRequestHandler handle
INFORMATION: Request: https://maps.googleapis.com/maps/api/directions/json?key=<MyApiCode>&mode=walking&origin=<Latitude>%2C<Longitude>&destination=<Latitude>%2C<Longitude>

**Comment by SippieCup** [comment]
Fixed this, issue was the bot using proprietary APIs, Fixed in latest release
