### ISSUE TITLE
can't log in

### ISSUE THREAD

**Issue by djuszko** [SwipeX/PokeMate#232]
Downloaded latest release, set config file, ran the .jar through command line. Getting this error:

```
Using default config.properties location
com.pokegoapi.exceptions.LoginFailedException: Failed to fetch token
        at com.pokegoapi.auth.PtcCredentialProvider.login(PtcCredentialProvider.
java:239)
        at com.pokegoapi.auth.PtcCredentialProvider.<init>(PtcCredentialProvider
.java:108)
        at com.pokegoapi.auth.PtcCredentialProvider.<init>(PtcCredentialProvider
.java:121)
        at dekk.pw.pokemate.Context.Login(Context.java:102)
        at dekk.pw.pokemate.Context.Login(Context.java:53)
        at dekk.pw.pokemate.PokeMate.<init>(PokeMate.java:59)
        at dekk.pw.pokemate.PokeMate.main(PokeMate.java:97)
Logged in as [REDACTED]
Exception in thread "main" com.pokegoapi.exceptions.LoginFailedException: Creden
tial Provider is null
        at com.pokegoapi.api.PokemonGo.<init>(PokemonGo.java:72)
        at dekk.pw.pokemate.PokeMate.<init>(PokeMate.java:62)
        at dekk.pw.pokemate.PokeMate.main(PokeMate.java:97)
```

Am I just doing something wrong? Tried different accounts, all doing the same thing.

**Comment by SippieCup** [comment]
If this is a gmail account make sure you use your full email addresses.

**Comment by djuszko** [comment]
Just figured it out. Turns out I'm an idiot. Didn't add @gmail.com

Was just about to delete this...
