### ISSUE TITLE
403 Error

### ISSUE THREAD

**Issue by umanghome** [SwipeX/PokeMate#238]
Getting a 403 error:

Logged in as umanghome@gmail.com
D/RequestHandler: Authenticated with static token
D/RequestHandler: Authenticated with static token
Exception in thread "main" com.pokegoapi.exceptions.RemoteServerException: Got a unexpected http code : 403
    at com.pokegoapi.main.RequestHandler.sendServerRequests(RequestHandler.java:111)
    at com.pokegoapi.api.player.PlayerProfile.updateProfile(PlayerProfile.java:90)
    at com.pokegoapi.api.player.PlayerProfile.<init>(PlayerProfile.java:78)
    at com.pokegoapi.api.PokemonGo.<init>(PokemonGo.java:82)
    at dekk.pw.pokemate.PokeMate.<init>(PokeMate.java:62)
    at dekk.pw.pokemate.PokeMate.main(PokeMate.java:93)

This is from my Digital Ocean droplet. The bot runs fine on my laptop. IP blacklisted?
Edit: The bot used to work fine on the droplet until this morning. I started two bots on the droplet last night.

**Comment by gsisso** [comment]
403 means forbidden,the only thing I can think of is try open a new droplet (maybe also in a different location then the current one) and see if you still get that,if you do then you'll need to try a different hosting company (maybe digital ocean side is the one blocking the request) and if that doesn't work either then niantic probably added extra security check (might be based on port 80 being open or dns look ups)

**Comment by SippieCup** [comment]
Yep, Looks like an IP ban.
