### ISSUE TITLE
Got the same Problem as before ( com.google.maps.OkHttpRequestHandler handle)

### ISSUE THREAD

**Issue by Shazgul** [SwipeX/PokeMate#246]
Still got the same Problem as before when starting the Bot under Ubuntu 16.04 with openJDK 8

D/RequestHandler: Authenticated with static token
Jul 31, 2016 11:21:27 PM com.google.maps.OkHttpRequestHandler handle
INFORMATION: Request: https://maps.googleapis.com/maps/api/directions/json?key=<Google Maps Token>&mode=walking&origin=<Latitude>%2C<Longitude>&destination=<Latitude>%2C<Longitude>

**Comment by SippieCup** [comment]
Is that all that is outputted?

I'm installing a ubuntu VM now and will test it.

**Comment by Shazgul** [comment]
Yes, multiple Times in a row, after "key=" appears the Google API, after "origin=" and "destination=" appears the latitude and longitude.

**Comment by gsisso** [comment]
this output is ok,its just mentioning its pulling way points from google directions api.

**Comment by SippieCup** [comment]
gsplash, it is an issue would be it outputting %2c (`,`) for origin and destination rather than the `lat,long`. Unless he is removing the co-ords in his post. Are you doing that?

If you aren't make sure you are defining Latitude and Longitude in the config.

**Comment by Shazgul** [comment]
i did removed the key, the latitude and the longitude. ;)
But it just shows me this Lines 8 Times in a Row and then nothing happens.
Before all these Lines just:

xxx@xxx-xxx:~/PokemonGoBot/SwipeX$ java -jar pokemate-all-0.2.3.5.jar 
Using default config.properties location
Logged in as xxx

Apears.

**Comment by SippieCup** [comment]
its running perfectly then.

**Comment by Shazgul** [comment]
But it doesnt show anything ? No Caught no nothing?

**Comment by SippieCup** [comment]
I'll take a look into it.

**Comment by SippieCup** [comment]
Try the new release and tell me if it continues.

**Comment by Shazgul** [comment]
Used version 0.3.1.3. now and getting following Error (I've replacd the Key, the Nickname, the Latitude and Longitude):

Using default config.properties location
Logged in as NICKNAME
Aug 01, 2016 9:43:28 AM com.google.maps.OkHttpRequestHandler handle
INFORMATION: Request: https://maps.googleapis.com/maps/api/directions/json?key=APIKEY&mode=walking&origin=LATITUDE%2CLONGITUDE&destination= LATITUDE%2CLONGITUDE
Aug 01, 2016 9:43:29 AM com.google.maps.OkHttpRequestHandler handle
INFORMATION: Request: https://maps.googleapis.com/maps/api/directions/json?key= APIKEY&mode=walking&origin= LATITUDE%2C12.37961124&destination= LATITUDE%2CLONGITUDE
Aug 01, 2016 9:43:29 AM com.google.maps.OkHttpRequestHandler handle
INFORMATION: Request: https://maps.googleapis.com/maps/api/directions/json?key= APIKEY&mode=walking&origin= LATITUDE%2CLONGITUDE&destination= LATITUDE%2CLONGITUDE
Aug 01, 2016 9:43:30 AM com.google.maps.OkHttpRequestHandler handle
INFORMATION: Request: https://maps.googleapis.com/maps/api/directions/json?key= APIKEY&mode=walking&origin= LATITUDE%2CLONGITUDE&destination= LATITUDE%2CLONGITUDE
Aug 01, 2016 9:43:30 AM com.google.maps.OkHttpRequestHandler handle
INFORMATION: Request: https://maps.googleapis.com/maps/api/directions/json?key= APIKEY&mode=walking&origin= LATITUDE%2CLONGITUDE&destination= LATITUDE%2CLONGITUDE
Aug 01, 2016 9:43:30 AM com.google.maps.OkHttpRequestHandler handle
INFORMATION: Request: https://maps.googleapis.com/maps/api/directions/json?key= APIKEY&mode=walking&origin= LATITUDE%2CLONGITUDE&destination= LATITUDE%2CLONGITUDE
Aug 01, 2016 9:43:30 AM com.google.maps.OkHttpRequestHandler handle
INFORMATION: Request: https://maps.googleapis.com/maps/api/directions/json?key= APIKEY&mode=walking&origin= LATITUDE%2CLONGITUDE&destination= LATITUDE%2CLONGITUDE
Aug 01, 2016 9:43:30 AM com.google.maps.OkHttpRequestHandler handle
INFORMATION: Request: https://maps.googleapis.com/maps/api/directions/json?key= APIKEY&mode=walking&origin= LATITUDE%2CLONGITUDE&destination= LATITUDE%2CLONGITUDE
Aug 01, 2016 9:43:30 AM com.google.maps.OkHttpRequestHandler handle
INFORMATION: Request: https://maps.googleapis.com/maps/api/directions/json?key= APIKEY&mode=walking&origin= LATITUDE%2CLONGITUDE&destination= LATITUDE%2CLONGITUDE
Aug 01, 2016 9:43:30 AM com.google.maps.OkHttpRequestHandler handle
INFORMATION: Request: https://maps.googleapis.com/maps/api/directions/json?key= APIKEY&mode=walking&origin= LATITUDE%2CLONGITUDE&destination= LATITUDE%2CLONGITUDE
Aug 01, 2016 9:43:31 AM com.google.maps.OkHttpRequestHandler handle
INFORMATION: Request: https://maps.googleapis.com/maps/api/directions/json?key= APIKEY&mode=walking&origin= LATITUDE%2CLONGITUDE&destination= LATITUDE%2CLONGITUDE
Aug 01, 2016 9:43:31 AM com.google.maps.OkHttpRequestHandler handle
INFORMATION: Request: https://maps.googleapis.com/maps/api/directions/json?key= APIKEY&mode=walking&origin= LATITUDE%2CLONGITUDE&destination= LATITUDE%2CLONGITUDE
Aug 01, 2016 9:43:31 AM com.google.maps.OkHttpRequestHandler handle
INFORMATION: Request: https://maps.googleapis.com/maps/api/directions/json?key= APIKEY&mode=walking&origin= LATITUDE%2CLONGITUDE&destination= LATITUDE%2CLONGITUDE
Aug 01, 2016 9:43:31 AM com.google.maps.OkHttpRequestHandler handle
INFORMATION: Request: https://maps.googleapis.com/maps/api/directions/json?key= APIKEY&mode=walking&origin= LATITUDE%2CLONGITUDE&destination= LATITUDE%2CLONGITUDE
Aug 01, 2016 9:43:31 AM com.google.maps.OkHttpRequestHandler handle
INFORMATION: Request: https://maps.googleapis.com/maps/api/directions/json?key= APIKEY&mode=walking&origin= LATITUDE%2CLONGITUDE&destination= LATITUDE%2CLONGITUDE
Aug 01, 2016 9:43:31 AM com.google.maps.OkHttpRequestHandler handle
INFORMATION: Request: https://maps.googleapis.com/maps/api/directions/json?key= APIKEY&mode=walking&origin= LATITUDE%2CLONGITUDE&destination= LATITUDE%2CLONGITUDE
D/RequestHandler: Authenticated with static token
Exception in thread "Timer-0" java.lang.NoClassDefFoundError: javafx/application/Application
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
    at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
    at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    at dekk.pw.pokemate.tasks.Update.run(Update.java:63)
    at dekk.pw.pokemate.tasks.TaskController$1.run(TaskController.java:57)
    at java.util.TimerThread.mainLoop(Timer.java:555)
    at java.util.TimerThread.run(Timer.java:505)
Caused by: java.lang.ClassNotFoundException: javafx.application.Application
    at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 16 more

Operating System:
Ubuntu 16.04.

Java version:
openjdk version "1.8.0_91"
OpenJDK Runtime Environment (build 1.8.0_91-8u91-b14-3ubuntu1~16.04.1-b14)
OpenJDK Server VM (build 25.91-b14, mixed mode)

**Comment by SippieCup** [comment]
Are you running the app without x11 running?

**Comment by SippieCup** [comment]
Also please update your java to 8 update 101

**Comment by Shazgul** [comment]
My config File: http://paste2.org/8K4DztPE

I'll try to update to 101 later, just must find out if 101 is out for Ubuntu.

**Comment by Shazgul** [comment]
Encountering with 0.3.1.5 now:

java -jar pokemate-all-0.3.1.5.jar 
Using default config.properties location
Logged in as xxx
Exception in thread "main" java.lang.NoClassDefFoundError: javafx/application/Application
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
    at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
    at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    at dekk.pw.pokemate.PokeMate.<init>(PokeMate.java:74)
    at dekk.pw.pokemate.PokeMate.main(PokeMate.java:97)
Caused by: java.lang.ClassNotFoundException: javafx.application.Application
    at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 14 more

**Comment by SippieCup** [comment]
This is an issue with a bad java installation, not PokeMate. For some reason you don't have JavaFX installed but you have the latest version of java.
