### ISSUE TITLE
After running for a while with UI, bot stops responding

### ISSUE THREAD

**Issue by ickis098** [SwipeX/PokeMate#251]
Noticed that already with some earlier releases, but after running for a while (20min in my last case) i get a bunch of exceptions and the bot then stops doing anything.

java.lang.NullPointerException
        at com.sun.prism.d3d.D3DTexture.getContext(D3DTexture.java:84)
        at com.sun.prism.d3d.D3DTexture.update(D3DTexture.java:207)
        at com.sun.prism.d3d.D3DTexture.update(D3DTexture.java:151)
        at com.sun.prism.impl.BaseContext.flushMask(BaseContext.java:109)
        at com.sun.prism.impl.BaseContext.drawQuads(BaseContext.java:118)
        at com.sun.prism.impl.VertexBuffer.flush(VertexBuffer.java:98)
        at com.sun.prism.impl.BaseContext.flushVertexBuffer(BaseContext.java:101)
        at com.sun.prism.impl.ps.BaseShaderContext.setRenderTarget(BaseShaderContext.java:746)
        at com.sun.prism.impl.BaseContext.setRenderTarget(BaseContext.java:131)
        at com.sun.prism.impl.BaseGraphics.<init>(BaseGraphics.java:105)
        at com.sun.prism.impl.ps.BaseShaderGraphics.<init>(BaseShaderGraphics.java:86)
        at com.sun.prism.d3d.D3DGraphics.<init>(D3DGraphics.java:42)
        at com.sun.prism.d3d.D3DGraphics.create(D3DGraphics.java:65)
        at com.sun.prism.d3d.D3DSwapChain.createGraphics(D3DSwapChain.java:131)
        at com.sun.javafx.tk.quantum.PresentingPainter.run(PresentingPainter.java:87)
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.util.concurrent.FutureTask.runAndReset(Unknown Source)
        at com.sun.javafx.tk.RenderJob.run(RenderJob.java:58)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(QuantumRenderer.java:125)
        at java.lang.Thread.run(Unknown Source)

**Comment by SwipeX** [comment]
This simply means the bot ran out of memory.

**Comment by ickis098** [comment]
Right, but can it be fixed?

**Comment by SwipeX** [comment]
run with `java -jar Pokemate.jar -Xmx8g`

**Comment by SippieCup** [comment]
Other than throwing more memory at it (like SwipeX suggested), nothing can be done until we move off of JavaFX. If you are running it for a long period, you probably have no need for the GUI anyway, I suggest disabling it unless you are actively debugging it or waiting for something specific and watching it intently.

Closing thread. We can continue the conversation on possible solutions on slack if you want more information.
