### ISSUE TITLE
Some bug in linux

### ISSUE THREAD

**Issue by ghost** [SwipeX/PokeMate#271]
Hi

There are some problem with linux, there is the list : 
- Images aren't showed [ > image appear only in notifications ](http://i.imgur.com/A21F1sb.png)
- Sometime it's crash but i think it's because the server is down so it's not your fault, but here somes logs `Exception in thread "JavaFX Application Thread" java.util.ConcurrentModificationException
  at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901)
  at java.util.ArrayList$Itr.next(ArrayList.java:851)
  at dekk.pw.pokemate.PokeMateUI.updatePokemon(PokeMateUI.java:404)
  at dekk.pw.pokemate.PokeMateUI.lambda$null$8(PokeMateUI.java:230)
  at com.sun.javafx.application.PlatformImpl.lambda$null$117(PlatformImpl.java:295)
  at java.security.AccessController.doPrivileged(Native Method)
  at com.sun.javafx.application.PlatformImpl.lambda$runLater$118(PlatformImpl.java:294)
  at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
  at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
  at com.sun.glass.ui.gtk.GtkApplication.lambda$null$450(GtkApplication.java:139)
  at java.lang.Thread.run(Thread.java:745)
  GoogleMapView.mapResized: triggering resize event
  `
  Openjfx is installed,
  thanks for reading

**Comment by SippieCup** [comment]
this is a JavaFX Bug and probably won't be fixed because we are moving away from javafx to a new GUI soon.

I suggest running without the GUI (use console notifications) and see how it does.

**Comment by ghost** [comment]
Ok, thanks
