### ISSUE TITLE
Crash when leveling up

### ISSUE THREAD

**Issue by giubil** [SwipeX/PokeMate#279]
Hello,

I am running pokemate with openjdk jre 8 headless,  and even with `show=false`, whenever I pass a level, the program crash telling me that I don't have javafx installed: 

```
Exception in thread "Timer-0" java.lang.NoClassDefFoundError: javafx/application/Application
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
    at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
    at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    at dekk.pw.pokemate.tasks.ConsoleGUIUpdate.header(ConsoleGUIUpdate.java:69)
    at dekk.pw.pokemate.tasks.ConsoleGUIUpdate.run(ConsoleGUIUpdate.java:39)
    at dekk.pw.pokemate.tasks.TaskController$1.run(TaskController.java:57)
    at java.util.TimerThread.mainLoop(Timer.java:555)
    at java.util.TimerThread.run(Timer.java:505)
Caused by: java.lang.ClassNotFoundException: javafx.application.Application
    at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 17 more
```

**Comment by kylestev** [comment]
@giubil give [0.3.2.4](https://github.com/SwipeX/PokeMate/releases/tag/0.3.2.4) a try and let me know if your issue is resolved.

**Comment by giubil** [comment]
@kylestev seems fixed to me, thanks :)
