### ISSUE TITLE
[Exception] Exception in thread "Timer-77" com.pokegoapi.exceptions.AsyncPokemonGoException: Unknown exception occurred. 

### ISSUE THREAD

**Issue by kyleshrader** [SwipeX/PokeMate#298]
This exception is halting the application

```
Exception in thread "Timer-77" com.pokegoapi.exceptions.AsyncPokemonGoException: Unknown exception occurred. 
    at com.pokegoapi.util.AsyncHelper.toBlocking(AsyncHelper.java:45)
    at com.pokegoapi.api.map.Map.getMapObjects(Map.java:406)
    at dekk.pw.pokemate.tasks.Navigate.populateRoute(Navigate.java:71)
    at dekk.pw.pokemate.tasks.Navigate.<init>(Navigate.java:44)
    at dekk.pw.pokemate.Walking$1.run(Walking.java:57)
    at java.util.TimerThread.mainLoop(Timer.java:555)
    at java.util.TimerThread.run(Timer.java:505)
Caused by: java.lang.RuntimeException: java.util.concurrent.ExecutionException: com.google.protobuf.InvalidProtocolBufferException: Contents of buffer are null
    at rx.exceptions.Exceptions.propagate(Exceptions.java:58)
    at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:465)
    at rx.observables.BlockingObservable.first(BlockingObservable.java:168)
    at com.pokegoapi.util.AsyncHelper.toBlocking(AsyncHelper.java:37)
    ... 6 more
Caused by: java.util.concurrent.ExecutionException: com.google.protobuf.InvalidProtocolBufferException: Contents of buffer are null
    at com.pokegoapi.main.RequestHandler$1.get(RequestHandler.java:109)
    at com.pokegoapi.main.RequestHandler$1.get(RequestHandler.java:86)
    at rx.internal.operators.OnSubscribeToObservableFuture$ToObservableFuture.call(OnSubscribeToObservableFuture.java:74)
    at rx.internal.operators.OnSubscribeToObservableFuture$ToObservableFuture.call(OnSubscribeToObservableFuture.java:43)
    at rx.Observable.unsafeSubscribe(Observable.java:9861)
    at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
    at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
    at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
    at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
    at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
    at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
    at rx.Observable.subscribe(Observable.java:9957)
    at rx.Observable.subscribe(Observable.java:9924)
    at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:445)
    ... 8 more
Caused by: com.google.protobuf.InvalidProtocolBufferException: Contents of buffer are null
    at com.pokegoapi.main.ServerRequest.getData(ServerRequest.java:78)
    at com.pokegoapi.main.RequestHandler.run(RequestHandler.java:292)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by Jarkheld** [comment]
i've got the same problem, version 0.3.3.1

**Comment by maxi2mc** [comment]
Server is currently down.

http://ispokemongodownornot.com/
