### ISSUE TITLE
Nullpointers

### ISSUE THREAD

**Issue by Jerry911** [SwipeX/PokeMate#321]
I keep getting this nullpointer exception after a few minutes. 
It only happens on 1 device, all the other devices don't run into this.

17 Aug 2016 10:05:29 [pool-2-thread-1] DEBUG Walking:49 - starting to walk
java.lang.NullPointerException
        at com.sun.prism.d3d.D3DTexture.getContext(D3DTexture.java:84)
        at com.sun.prism.d3d.D3DTexture.update(D3DTexture.java:207)
        at com.sun.prism.d3d.D3DTexture.update(D3DTexture.java:151)
        at com.sun.prism.impl.BaseContext.flushMask(BaseContext.java:109)
        at com.sun.prism.impl.BaseContext.drawQuads(BaseContext.java:118)
        at com.sun.prism.impl.VertexBuffer.flush(VertexBuffer.java:98)
        at com.sun.prism.impl.BaseContext.flushVertexBuffer(BaseContext.java:101
)
        at com.sun.prism.impl.ps.BaseShaderContext.setRenderTarget(BaseShaderCon
text.java:746)
        at com.sun.prism.impl.BaseContext.setRenderTarget(BaseContext.java:131)
        at com.sun.prism.impl.ps.BaseShaderContext.checkState(BaseShaderContext.
java:644)
        at com.sun.prism.impl.ps.BaseShaderContext.validateTextureOp(BaseShaderC
ontext.java:583)
        at com.sun.prism.impl.ps.BaseShaderContext.validateTextureOp(BaseShaderC
ontext.java:500)
        at com.sun.prism.impl.BaseGraphics.drawTexture(BaseGraphics.java:419)
        at com.sun.prism.impl.ps.BaseShaderGraphics.drawTexture(BaseShaderGraphi
cs.java:139)
        at com.sun.javafx.webkit.prism.WCPageBackBufferImpl.flush(WCPageBackBuff
erImpl.java:68)
        at com.sun.webkit.WebPage.paint(WebPage.java:670)
        at com.sun.javafx.sg.prism.web.NGWebView.renderContent(NGWebView.java:96
)
        at com.sun.javafx.sg.prism.NGNode.doRender(NGNode.java:2053)
        at com.sun.javafx.sg.prism.NGNode.render(NGNode.java:1945)
        at com.sun.javafx.sg.prism.NGGroup.renderContent(NGGroup.java:235)
        at com.sun.javafx.sg.prism.NGRegion.renderContent(NGRegion.java:576)
        at com.sun.javafx.sg.prism.NGNode.doRender(NGNode.java:2053)
        at com.sun.javafx.sg.prism.NGNode.render(NGNode.java:1945)
        at com.sun.javafx.sg.prism.NGGroup.renderContent(NGGroup.java:235)
        at com.sun.javafx.sg.prism.NGRegion.renderContent(NGRegion.java:576)
        at com.sun.javafx.sg.prism.NGNode.doRender(NGNode.java:2053)
        at com.sun.javafx.sg.prism.NGNode.render(NGNode.java:1945)
        at com.sun.javafx.tk.quantum.ViewPainter.doPaint(ViewPainter.java:477)
        at com.sun.javafx.tk.quantum.ViewPainter.paintImpl(ViewPainter.java:330)

```
    at com.sun.javafx.tk.quantum.PresentingPainter.run(PresentingPainter.jav
```

a:91)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:51
1)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at com.sun.javafx.tk.RenderJob.run(RenderJob.java:58)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.
java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor
.java:617)
        at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(Quantu
mRenderer.java:125)
        at java.lang.Thread.run(Thread.java:745)
java.lang.NullPointerException
java.lang.NullPointerException
java.lang.NullPointerException
java.lang.NullPointerException
java.lang.NullPointerException
java.lang.NullPointerException
java.lang.NullPointerException
java.lang.NullPointerException
java.lang.NullPointerException
java.lang.NullPointerException
java.lang.NullPointerException
java.lang.NullPointerException

**Comment by gsisso** [comment]
this exception is usually due to not having enough ram. just disable the ui option

**Comment by ianket** [comment]
I don't believe this error is associated to ram, i allocated 8GB of ram and it still occurs

**Comment by gsisso** [comment]
well no one is going to fix it as they are working on the new ui so its either disable it or just re-run everytime it crashes
