### ISSUE TITLE
Null Pointer Error (Disabled GUI and read other errors on this bot)

### ISSUE THREAD

**Issue by KingMatt123** [SwipeX/PokeMate#325]
Hi, I'm getting this error. I've read other errors regarding this bot, but none of them seem to be mine. I have also disable The GUI and have 16 gb of ram. He is the log:

C:\Users\matthew\Desktop\myBot>java -jar pokemate-all-0.4.2.jar
05 Sep 2016 16:52:29 [main] INFO  PokeMate:118 - Using default config.properties location
05 Sep 2016 16:52:30 [main] INFO  PokeMate:73 - Using Coordinates -37.810992552782515, 144.96334924665396
D/GoogleUserCredentialProvider: 3600
D/GoogleUserCredentialProvider: Refreshed Token eyJhbGciOiJSUzI1NiIsImtpZCI6IjI1OTM5NzFjYzRhMjExZWYwYzcwNmZjM2Q4MDg1ODBiMWI5ZTU0MjAifQ.eyJpc3MiOiJodHRwczovL2FjY291bnRzLmdvb2dsZS5jb20iLCJhdF9oYXNoIjoiTnF1Wm5oaFJRQzlGQUUzZklyZnRsZyIsImF1ZCI6Ijg0ODIzMjUxMTI0MC03M3JpM3Q3cGx2azk2cGo0Zjg1dWo4b3RkYXQyYWxlbS5hcHBzLmdvb2dsZXVzZXJjb250ZW50LmNvbSIsInN1YiI6IjExMDczNTg5MDg1NjA5NzM3MDYwOSIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJhenAiOiI4NDgyMzI1MTEyNDAtNzNyaTN0N3Bsdms5NnBqNGY4NXVqOG90ZGF0MmFsZW0uYXBwcy5nb29nbGV1c2VyY29udGVudC5jb20iLCJlbWFpbCI6Im1hdHRoZXdtcnVnYWxhQGdtYWlsLmNvbSIsImlhdCI6MTQ3MzA1ODQ5MiwiZXhwIjoxNDczMDYyMDkyfQ.VP5pct_mHYEkVFUdNN8AcxNoJ9kVIFwilowkakOCMS9-3QKHkcj8TFl-x_cmIBr2-LZdEl_Y-dAVOkwvIMbJqJ6SdKIUwx34iJ8Q9qKi3yQa0ZPV_VrbKFGwucC019tq-3_VJmJUx7Gt_I6iy54eTptSmotQeDr47GTm_kh5v1hgHIQipdM6Q-ZdYwPUWvyymp8gEOrKX1GThAkP_CMcJGnDN_mVeJhh1CXxE1-cbH28xBx_5Z7BZ0Q-4e66YC1YUApJxqrr33z1IMtfdUwyQ1HZl35xtJDsCGBFV-6OGnTGRVcc81jWmm_nnHgB9U5xGk6al7BB18HkBepWH0fRnQ
05 Sep 2016 16:52:31 [main] INFO  PokeMate:78 - Logged in as ***
D/RequestHandler: Authenticated with static token
05 Sep 2016 16:52:38 [main] ERROR Navigate:113 - Null pointer error.
java.lang.NullPointerException
        at dekk.pw.pokemate.tasks.Navigate.populateRoute(Navigate.java:78) [pokemate-all-0.4.2.jar:0.4.1]
        at dekk.pw.pokemate.tasks.Navigate.<init>(Navigate.java:52) [pokemate-all-0.4.2.jar:0.4.1]
        at dekk.pw.pokemate.tasks.TaskController.<init>(TaskController.java:24) [pokemate-all-0.4.2.jar:0.4.1]
        at dekk.pw.pokemate.PokeMate.<init>(PokeMate.java:109) [pokemate-all-0.4.2.jar:0.4.1]
        at dekk.pw.pokemate.PokeMate.main(PokeMate.java:130) [pokemate-all-0.4.2.jar:0.4.1]

C:\Users\matthew\Desktop\myBot>

**Comment by KingMatt123** [comment]
I was running Java 8, but still did an update to get a newer version. I fixed the error above, but now it's saying that my account may be banned but I know that it is not.

**Comment by KingMatt123** [comment]
Fixed it! I was authorizing access with the wrong gmail account!
