### ISSUE TITLE
Error when compiling.

### ISSUE THREAD

**Issue by jeffsnow88** [SwipeX/PokeMate#40]
Hello all. Excellent work guys.

I have being trying to compile the code, but there are some errors.

> errors

**Comment by SwipeX** [comment]
You need gradle, I would reccommend IntellIJ IDEA

**Comment by jeffsnow88** [comment]
thanks for your info. I have it installed but the error keeps. As per the error, its appears that the could was not able to  make some imports. Any other idea?

**Comment by SwipeX** [comment]
Do you have Java 8? Is the project imported under Gradle?

**Comment by jeffsnow88** [comment]
Now i see, I have not created a project, i was trying to execute compiling via javac on cmd (jdk 8.0 is installed).  I will download the gradle that you mentioned.

**Comment by SwipeX** [comment]
It comes pre bundled.

**Comment by SwipeX** [comment]
just do file-> new project from vcs -> github -> paste in git link to this repo -> run gradle.build -> profit

**Comment by jeffsnow88** [comment]
Managed to compile it with your help! Thanks. However, getting error when trying to log in:

Logged in as xxxx@gmail.com
com.pokegoapi.exceptions.LoginFailedException
    at com.pokegoapi.auth.GoogleLogin.login(GoogleLogin.java:103)
    at dekk.pw.pokemate.Context.Login(Context.java:46)
    at dekk.pw.pokemate.Context.Login(Context.java:38)
    at dekk.pw.pokemate.PokeMate.<init>(PokeMate.java:39)
    at dekk.pw.pokemate.PokeMate.main(PokeMate.java:55)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
Exception in thread "main" java.lang.NullPointerException
D/RequestHandler: Authenticated with static token
    at POGOProtos.Networking.Envelopes.RequestEnvelopeOuterClass$RequestEnvelope$Builder.setAuthInfo(RequestEnvelopeOuterClass.java:2451)
    at com.pokegoapi.main.RequestHandler.resetBuilder(RequestHandler.java:255)
    at com.pokegoapi.main.RequestHandler.resetBuilder(RequestHandler.java:241)
    at com.pokegoapi.main.RequestHandler.<init>(RequestHandler.java:64)
    at com.pokegoapi.api.PokemonGo.<init>(PokemonGo.java:64)
    at dekk.pw.pokemate.PokeMate.<init>(PokeMate.java:41)
    at dekk.pw.pokemate.PokeMate.main(PokeMate.java:55)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)

Process finished with exit code 1

**Comment by jeffsnow88** [comment]
working, i think it was proxy issues, Thanks a lot man,

**Comment by eBunny6** [comment]
How did u resolve that issue. Everything i get is:
To run a build, run gradle <task> ...

To see a list of available tasks, run gradle tasks

To see a list of command-line options, run gradle --help

To see more detail about a task, run gradle help --task <task>

BUILD SUCCESSFUL

Total time: 4.165 secs

Process finished with exit code 0

And then nothing...

**Comment by eBunny6** [comment]
@jeffsnow88 How did u resolve that proxy issues?
