### ISSUE TITLE
Google API Key Issue

### ISSUE THREAD

**Issue by FreakySt0rm** [SwipeX/PokeMate#42]
I'm getting:

INFO: Request: https://maps.googleapis.com/maps/api/directions/json?key=**************************************0&mode=walking&origin=533771067.00000000%2C-2729010.00000000&destination=533771066.97144836%2C-2729009.99476281
com.google.maps.errors.RequestDeniedException: This API project is not authorized to use this API. Please ensure this API is activated in the Google Developers
Console: https://console.developers.google.com/apis/api/directions_backend?project=_
        at com.google.maps.errors.ApiException.from(ApiException.java:50)
        at com.google.maps.DirectionsApi$Response.getError(DirectionsApi.java:75
)
        at com.google.maps.internal.OkHttpPendingResult.parseResponse(OkHttpPend
ingResult.java:270)
        at com.google.maps.internal.OkHttpPendingResult.await(OkHttpPendingResul
t.java:167)
        at com.google.maps.PendingResultBase.await(PendingResultBase.java:56)
        at dekk.pw.pokemate.tasks.Navigate.queryDirections(Navigate.java:61)
        at dekk.pw.pokemate.tasks.Navigate.populateDirections(Navigate.java:83)
        at dekk.pw.pokemate.tasks.Navigate.<init>(Navigate.java:31)
        at dekk.pw.pokemate.tasks.TaskController.<init>(TaskController.java:20)
        at dekk.pw.pokemate.PokeMate.<init>(PokeMate.java:49)
        at dekk.pw.pokemate.PokeMate.main(PokeMate.java:55)
Jul 25, 2016 9:34:15 PM com.google.maps.OkHttpRequestHandler handle

Could you advise exactly what type of API Key is required for the walking module? I issued a Google Maps Javascript Server SPI key, but this doesn't seem to be working. Which of these do I need?:

Google Maps APIs

Google Maps Android API
Google Maps SDK for iOS
Google Maps JavaScript API
Google Places API for Android
Google Places API for iOS
Google Maps Roads API
Google Static Maps API
Google Street View Image API
Google Maps Embed API
Google Places API Web Service
Google Maps Geocoding API
Google Maps Directions API
Google Maps Distance Matrix API
Google Maps Geolocation API
Google Maps Elevation API
Google Maps Time Zone API

And do they need to be Server or Browser enabled?

Other than that, AWESOME work SwipeX :D

**Comment by kyleshrader** [comment]
It just needs to be a browser api key.

https://developers.google.com/maps/documentation/javascript/get-api-key

Hit "Get Key" > Create a project > give the key a name > copy-pasta

**Comment by FreakySt0rm** [comment]
Forget this - The API Key was correct, I hadn't updated the new config.properties, so incorrect parameters were being passed to the HTTP request. My bad!

**Comment by FreakySt0rm** [comment]
Profile update : 912229 XP on LVL 26 6.11 % to LVL 27 - Gained 210 XP - XP/H: 45
06 - Runtime: 00:02:47
Exception in thread "JavaFX Application Thread" java.lang.NullPointerException
        at com.pokegoapi.api.inventory.CandyJar.getCandies(CandyJar.java:80)
        at com.pokegoapi.api.pokemon.Pokemon.getCandy(Pokemon.java:150)
        at dekk.pw.pokemate.PokeMateUI.lambda$null$5(PokeMateUI.java:162)
        at com.sun.javafx.application.PlatformImpl.lambda$null$173(PlatformImpl.
java:295)
        at java.security.AccessController.doPrivileged(Native Method)
        at com.sun.javafx.application.PlatformImpl.lambda$runLater$174(PlatformI
mpl.java:294)
        at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatch
er.java:95)
        at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
        at com.sun.glass.ui.win.WinApplication.lambda$null$148(WinApplication.ja
va:191)
        at java.lang.Thread.run(Unknown Source)

**Comment by FreakySt0rm** [comment]
Checking the journal on my actual app, the script SEEMS to be working as I can see pokestops tagged and pokemon caught, but still getting these exceptions thrown every cycle and the 3 columns on the UI just display "Loading"
