### ISSUE TITLE
0.1.8 error CandyJar

### ISSUE THREAD

**Issue by dubcanada** [SwipeX/PokeMate#46]
Hello,

I am getting an error when trying to run the latest version, 0.1.5 was perfectly fine.

```
Exception in thread "JavaFX Application Thread" java.lang.NullPointerException
    at com.pokegoapi.api.inventory.CandyJar.getCandies(CandyJar.java:80)
    at com.pokegoapi.api.pokemon.Pokemon.getCandy(Pokemon.java:150)
    at dekk.pw.pokemate.PokeMateUI.lambda$null$5(PokeMateUI.java:162)
    at com.sun.javafx.application.PlatformImpl.lambda$null$173(PlatformImpl.java:295)
    at java.security.AccessController.doPrivileged(Native Method)
    at com.sun.javafx.application.PlatformImpl.lambda$runLater$174(PlatformImpl.java:294)
    at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
```

**Comment by dubcanada** [comment]
Seems the error is fixed in this pull request - https://github.com/Grover-c13/PokeGOAPI-Java/pull/225/files
