### ISSUE TITLE
NullPointerEx Graphics Bug

### ISSUE THREAD

**Issue by MrMonotone** [SwipeX/PokeMate#55]
java.lang.NullPointerException
    at com.sun.prism.d3d.D3DTexture.getContext(D3DTexture.java:84)
    at com.sun.prism.d3d.D3DTexture.update(D3DTexture.java:207)
    at com.sun.prism.d3d.D3DTexture.update(D3DTexture.java:151)
    at com.sun.prism.impl.BaseContext.flushMask(BaseContext.java:109)
    at com.sun.prism.impl.BaseContext.drawQuads(BaseContext.java:118)
    at com.sun.prism.impl.VertexBuffer.flush(VertexBuffer.java:98)
    at com.sun.prism.impl.BaseContext.flushVertexBuffer(BaseContext.java:101)
    at com.sun.prism.impl.ps.BaseShaderContext.setRenderTarget(BaseShaderContext.java:746)
    at com.sun.prism.impl.BaseContext.setRenderTarget(BaseContext.java:131)
    at com.sun.prism.impl.BaseGraphics.<init>(BaseGraphics.java:105)
    at com.sun.prism.impl.ps.BaseShaderGraphics.<init>(BaseShaderGraphics.java:86)
    at com.sun.prism.d3d.D3DGraphics.<init>(D3DGraphics.java:42)
    at com.sun.prism.d3d.D3DGraphics.create(D3DGraphics.java:65)
    at com.sun.prism.d3d.D3DSwapChain.createGraphics(D3DSwapChain.java:131)
    at com.sun.javafx.tk.quantum.PresentingPainter.run(PresentingPainter.java:87)
    at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
    at java.util.concurrent.FutureTask.runAndReset(Unknown Source)
    at com.sun.javafx.tk.RenderJob.run(RenderJob.java:58)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(QuantumRenderer.java:125)
    at java.lang.Thread.run(Unknown Source)

Does not crash the program. Just removes the pokemon UI and the lines drawn on the map

**Comment by SwipeX** [comment]
Duplicate #30
