### ISSUE TITLE
Error spammed in console.

### ISSUE THREAD

**Issue by null-dev** [SwipeX/PokeMate#57]
This has been happening since I cloned the latest master (didn't test previous versions).

```
Exception in thread "JavaFX Application Thread" netscape.javascript.JSException: Invalid function reference
    at com.sun.webkit.dom.JSObject.callImpl(Native Method)
    at com.sun.webkit.dom.JSObject.call(JSObject.java:98)
    at com.lynden.gmapsfx.javascript.JavascriptObject.invokeJavascript(JavascriptObject.java:230)
    at com.lynden.gmapsfx.javascript.object.InfoWindow.setContent(InfoWindow.java:67)
    at dekk.pw.pokemate.PokeMateUI.lambda$null$5(PokeMateUI.java:156)
    at com.sun.javafx.application.PlatformImpl.lambda$null$173(PlatformImpl.java:295)
    at java.security.AccessController.doPrivileged(Native Method)
    at com.sun.javafx.application.PlatformImpl.lambda$runLater$174(PlatformImpl.java:294)
    at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
    at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
    at com.sun.glass.ui.gtk.GtkApplication.lambda$null$49(GtkApplication.java:139)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by SwipeX** [comment]
definitely has to do with the UI. Didn't get this in testing, so I'm curious as to what the issue is.

**Comment by SonnyX** [comment]
@null-dev Gnome <3

**Comment by null-dev** [comment]
@SonnyX Actually, I don't use Gnome, I use plain old Openbox.

But yeah, I guess JavaFX is using GTK...
