### ISSUE TITLE
Got an error

### ISSUE THREAD

**Issue by elmagow** [SwipeX/PokeMate#69]
Just got this in the terminal, don't really know what it mean, but maybe it is usefull for debug?

`Exception in thread "Thread-2" java.util.ConcurrentModificationException
    at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901)
    at java.util.ArrayList$Itr.next(ArrayList.java:851)
    at dekk.pw.pokemate.tasks.EvolvePokemon.run(EvolvePokemon.java:36)
    at dekk.pw.pokemate.tasks.TaskController.lambda$run$0(TaskController.java:41)
    at dekk.pw.pokemate.tasks.TaskController$$Lambda$199/403238717.accept(Unknown Source)
    at java.util.ArrayList.forEach(ArrayList.java:1249)
    at dekk.pw.pokemate.tasks.TaskController.run(TaskController.java:41)`

**Comment by SwipeX** [comment]
Thanks. This has been fixed afaik by a sync block, it should reflect in the next build.

**Comment by SippieCup** [comment]
Let me know if the sync block fixes it, I am not sure it will because it is removing elements from the list itself and may not be a threading issue. If it doesn't a good fix would be to convert the for loops containing the list of pokemon to an iterator. This would allow us to never have an issue with concurrent modifications.

**Comment by SwipeX** [comment]
@SippieCup oops. You are 100% correct. The issue is the indexing AFTER a pokemon evolves.

**Comment by SippieCup** [comment]
This has been fixed (my first contribution!)
