### ISSUE TITLE
UI not working 

### ISSUE THREAD

**Issue by DonMoritz** [SwipeX/PokeMate#80]
Hey,
I actually dont know if i did something wrong or there is an error. 
But running PokeMate in IntelliJ works fine. When I start PokeMateUI while PokeMate is still running it gives me this error in the console:

Exception in thread "JavaFX Application Thread" java.lang.NullPointerException
    at dekk.pw.pokemate.PokeMateUI.mapInitialized(PokeMateUI.java:78)
    at com.lynden.gmapsfx.GoogleMapView.fireMapInitializedListeners(GoogleMapView.java:470)
    at com.lynden.gmapsfx.GoogleMapView.initialiseScript(GoogleMapView.java:328)
    at com.lynden.gmapsfx.GoogleMapView.access$000(GoogleMapView.java:50)
    at com.lynden.gmapsfx.GoogleMapView$3.changed(GoogleMapView.java:305)
    at com.lynden.gmapsfx.GoogleMapView$3.changed(GoogleMapView.java:302)
    at com.sun.javafx.binding.ExpressionHelper$SingleChange.fireValueChangedEvent(ExpressionHelper.java:182)
    at com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:81)
    at javafx.beans.property.ReadOnlyObjectPropertyBase.fireValueChangedEvent(ReadOnlyObjectPropertyBase.java:74)
    at javafx.beans.property.ReadOnlyObjectWrapper.fireValueChangedEvent(ReadOnlyObjectWrapper.java:102)
    at javafx.beans.property.ObjectPropertyBase.markInvalid(ObjectPropertyBase.java:112)
    at javafx.beans.property.ObjectPropertyBase.set(ObjectPropertyBase.java:146)
    at javafx.scene.web.WebEngine$LoadWorker.updateState(WebEngine.java:1260)
    at javafx.scene.web.WebEngine$LoadWorker.dispatchLoadEvent(WebEngine.java:1371)
    at javafx.scene.web.WebEngine$LoadWorker.access$1200(WebEngine.java:1253)
    at javafx.scene.web.WebEngine$PageLoadListener.dispatchLoadEvent(WebEngine.java:1240)
    at com.sun.webkit.WebPage.fireLoadEvent(WebPage.java:2416)
    at com.sun.webkit.WebPage.fwkFireLoadEvent(WebPage.java:2260)
    at com.sun.webkit.network.URLLoader.twkDidFinishLoading(Native Method)
    at com.sun.webkit.network.URLLoader.notifyDidFinishLoading(URLLoader.java:838)
    at com.sun.webkit.network.URLLoader.lambda$didFinishLoading$98(URLLoader.java:829)
    at com.sun.javafx.application.PlatformImpl.lambda$null$173(PlatformImpl.java:295)
    at java.security.AccessController.doPrivileged(Native Method)
    at com.sun.javafx.application.PlatformImpl.lambda$runLater$174(PlatformImpl.java:294)
    at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
    at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
    at com.sun.glass.ui.win.WinApplication.lambda$null$148(WinApplication.java:191)
    at java.lang.Thread.run(Thread.java:745)

The Winwow pops up, but nothing is shown except the basics and loading.

**Comment by SwipeX** [comment]
Don't run `PokeMateUI`, just change show=true in your properties and run `PokeMate`

**Comment by DonMoritz** [comment]
;) Solved thank you nice little programm. Works like a charm for me now
