### ISSUE TITLE
[BUG] ToastMessages should only execute when UI mode is active.

### ISSUE THREAD

**Issue by SonnyX** [SwipeX/PokeMate#99]
Title explains it all :)

```
Exception in thread "Thread-1" java.lang.IllegalStateException: Toolkit not initialized
    at com.sun.javafx.application.PlatformImpl.runLater(PlatformImpl.java:273)
    at com.sun.javafx.application.PlatformImpl.runLater(PlatformImpl.java:268)
    at javafx.application.Platform.runLater(Platform.java:83)
    at dekk.pw.pokemate.PokeMateUI.toast(PokeMateUI.java:244)
    at dekk.pw.pokemate.tasks.CatchPokemon.run(CatchPokemon.java:55)
    at dekk.pw.pokemate.tasks.TaskController.lambda$run$0(TaskController.java:41)
    at java.util.ArrayList.forEach(ArrayList.java:1249)
    at dekk.pw.pokemate.tasks.TaskController.run(TaskController.java:41)
```

**Comment by BurakDev** [comment]
And show old messages on console if UI mode is disabled.

**Comment by SonnyX** [comment]
This should fix it:

```
    public static void toast(String message) {
        if(Config.isShowUI()) Platform.runLater(() ->
                mapComponent.getWebview().getEngine().executeScript(
                        "$.notify(\"" + message + "\", {\n\tanimate: {\n\t\tenter: \'animated bounceInDown\',\n\t\texit: \'animated bounceOutUp\'\n\t}\n});"));
        else System.out.println(message);
    }
```

**Comment by BurakDev** [comment]
LGTM, I think you can make a pull request of this

**Comment by BurakDev** [comment]
The fix was merged, can you try to reproduce this ?
